datasource:
  hikari:
    connection-test-query: SELECT 1 FROM DUAL
    minimum-idle: 1
    maximum-pool-size: 5
  driverclassname: org.h2.Driver
  url: jdbc:h2:~/test
  username: sa
  password:
  initializationmode: always
  initsql:
    - schema.sql
    - data.sql