INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (1, 'Avert', '23', '07095',1,1);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (2, 'Brodway', '231', '07097',1,1);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (3, 'Sdef', '5', '07092',1,1);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (4, 'Esdr', '67', '07079',1,1);

INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (5, 'Sdcf', '123', '07097',2,2);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (6, 'Qwser', '1', '07090',2,2);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (7, 'Qasww', '111', '07095',2,2);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (8, 'Avess', '23', '07095',2,2);

INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (9, 'Broy', '231', '07097',3,3);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (10, 'Sdeqwe', '5', '07092',3,3);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (11, 'Esdtyyy', '67', '07079',3,3);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (12, 'Sdesss', '123', '07097',3,3);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (13, 'Qqwtttt', '1', '07090',3,3);
INSERT INTO ADDRESS (ID,STREET,HOUSE_NUMBER,ZIP_CODE,PRBR_ID,COMPANY_ID) VALUES (14, 'Qartyh', '111', '07095',3,3);

INSERT INTO COMPANY (ID,NAME,PRBR_ID) VALUES (1, 'IntyerInc',1);
INSERT INTO COMPANY (ID,NAME,PRBR_ID) VALUES (2, 'IntyerInc2',2);
INSERT INTO COMPANY (ID,NAME,PRBR_ID) VALUES (3, 'IntyerInc3',3);